version: '3'
services:
  worker:
    build:
      context: ./celery-worker
      dockerfile: Dockerfile
    volumes:
      - ./:/celery-worker
      - ./media/input:/celery-worker/input
      - ./media/output:/celery-worker/output
    command: celery worker -A celery-worker.tasks -l info -n celery-worker@%h
    depends_on:
      - redis
  scheduler:
    build:
      context: ./scheduler
      dockerfile: Dockerfile
    volumes:
      - ./:/scheduler
      - ./media/input:/scheduler/input
      - ./media/output:/scheduler/output
    entrypoint:
      - python
    command: scheduler/run.py
    depends_on:
      - redis
  monitor:
    image: mher/flower:latest
    ports:
     - "5555:5555"
    entrypoint: flower
    command: --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis
